--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/smallkingdev-pm-pl/AlwaysDay
build-by-default: true
branches:
- main
projects:
  AlwaysDay:
    path: ""
    icon: icon.png
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.0
...
