name: AlwaysDay
main: SmallkingDev\AlwaysDay\Main
src-namespace-prefix: SmallkingDev\AlwaysDay
version: 1.1.0
api: [4.0.0, 5.0.0]
author: SmallkingDev
description: Always leave it in the day time!
website: https://github.com/smallkingdev-pm-pl/AlwaysDay
